### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mozork01** [mindsh4ke/witch-mobility-mod#6]
Fabric 1.20.1

My game crashed when I pressed the ctrl key while aiming at a broom with my cursor.

[crash-2024-03-09_16.13.46-client.txt](https://github.com/mindsh4ke/witch-mobility-mod/files/14546725/crash-2024-03-09_16.13.46-client.txt)

**Comment by mindsh4ke** [comment]
Hi, Witch Mobility is only available for 1.20.2, 1.20 and 1.20.1 versions might not work properly, sorry for the confusion.
